-- Tickets omnichannel: atendentes, skills, matriz de triagem, tickets,
-- conversa, anexos, trilha de eventos e notificações.

ALTER TABLE admin_users
  ADD CONSTRAINT CK_ADMIN_USERS_ROLE CHECK (role IN ('USER', 'EMPLOYEE', 'ADMIN'));

CREATE TABLE skills (
    id   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    code VARCHAR2(40 CHAR)  NOT NULL,
    name VARCHAR2(100 CHAR) NOT NULL,
    CONSTRAINT PK_SKILLS PRIMARY KEY (id),
    CONSTRAINT UQ_SKILLS_CODE UNIQUE (code)
);

CREATE TABLE employees (
    id                  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id             NUMBER(19) NOT NULL,
    presence            VARCHAR2(10 CHAR) DEFAULT 'OFFLINE' NOT NULL,
    presence_changed_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    last_assigned_at    TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (id),
    CONSTRAINT UQ_EMPLOYEES_USER UNIQUE (user_id),
    CONSTRAINT FK_EMPLOYEES_USER FOREIGN KEY (user_id) REFERENCES admin_users (id),
    CONSTRAINT CK_EMPLOYEES_PRESENCE CHECK (presence IN ('ONLINE', 'AUSENTE', 'OFFLINE'))
);

CREATE TABLE employee_skills (
    employee_id NUMBER(19) NOT NULL,
    skill_id    NUMBER(19) NOT NULL,
    CONSTRAINT PK_EMPLOYEE_SKILLS PRIMARY KEY (employee_id, skill_id),
    CONSTRAINT FK_EMP_SKILLS_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id),
    CONSTRAINT FK_EMP_SKILLS_SKILL FOREIGN KEY (skill_id) REFERENCES skills (id)
);

CREATE TABLE ticket_tipo_config (
    segment            VARCHAR2(30 CHAR)  NOT NULL,
    label              VARCHAR2(100 CHAR) NOT NULL,
    skill_id           NUMBER(19) NOT NULL,
    queue              VARCHAR2(20 CHAR)  NOT NULL,
    default_priority   VARCHAR2(10 CHAR)  NOT NULL,
    sla_minutes        NUMBER(10) NOT NULL,
    escalation_minutes NUMBER(10) NOT NULL,
    active             BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT PK_TICKET_TIPO_CONFIG PRIMARY KEY (segment),
    CONSTRAINT FK_TIPO_CONFIG_SKILL FOREIGN KEY (skill_id) REFERENCES skills (id),
    CONSTRAINT CK_TIPO_CONFIG_SEGMENT CHECK (segment IN ('DEFEITO_APP', 'PROBLEMA_PEDIDO', 'FEEDBACK_SUGESTAO')),
    CONSTRAINT CK_TIPO_CONFIG_QUEUE CHECK (queue IN ('TECNOLOGIA', 'MARKETPLACE', 'PRODUTO')),
    CONSTRAINT CK_TIPO_CONFIG_PRIORITY CHECK (default_priority IN ('NORMAL', 'ALTA', 'CRITICA')),
    CONSTRAINT CK_TIPO_CONFIG_MINUTES CHECK (sla_minutes > 0 AND escalation_minutes > 0)
);

CREATE TABLE tickets (
    id                       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id                  NUMBER(19) NOT NULL,
    segment                  VARCHAR2(30 CHAR) NOT NULL,
    description              VARCHAR2(2000 CHAR) NOT NULL,
    channel                  VARCHAR2(20 CHAR) DEFAULT 'APP' NOT NULL,
    status                   VARCHAR2(20 CHAR) DEFAULT 'ABERTO' NOT NULL,
    priority                 VARCHAR2(10 CHAR) DEFAULT 'NORMAL' NOT NULL,
    assigned_employee_id     NUMBER(19),
    sla_started_at           TIMESTAMP(6) WITH TIME ZONE,
    sla_due_at               TIMESTAMP(6) WITH TIME ZONE,
    engineering_alert        BOOLEAN DEFAULT FALSE NOT NULL,
    engineering_alert_reason VARCHAR2(500 CHAR),
    created_at               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    assumed_at               TIMESTAMP(6) WITH TIME ZONE,
    resolved_at              TIMESTAMP(6) WITH TIME ZONE,
    closed_at                TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_TICKETS PRIMARY KEY (id),
    CONSTRAINT FK_TICKETS_USER FOREIGN KEY (user_id) REFERENCES admin_users (id),
    CONSTRAINT FK_TICKETS_SEGMENT FOREIGN KEY (segment) REFERENCES ticket_tipo_config (segment),
    CONSTRAINT FK_TICKETS_EMPLOYEE FOREIGN KEY (assigned_employee_id) REFERENCES employees (id),
    CONSTRAINT CK_TICKETS_CHANNEL CHECK (channel IN ('APP', 'CHATBOT_IA')),
    CONSTRAINT CK_TICKETS_STATUS CHECK (status IN ('ABERTO', 'EM_FILA', 'EM_ATENDIMENTO', 'ESCALADO', 'RESOLVIDO', 'FECHADO')),
    CONSTRAINT CK_TICKETS_PRIORITY CHECK (priority IN ('NORMAL', 'ALTA', 'CRITICA'))
);

CREATE TABLE ticket_messages (
    id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ticket_id      NUMBER(19) NOT NULL,
    sender_type    VARCHAR2(10 CHAR) NOT NULL,
    sender_user_id NUMBER(19),
    body           VARCHAR2(2000 CHAR) NOT NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TICKET_MESSAGES PRIMARY KEY (id),
    CONSTRAINT FK_TICKET_MSG_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT FK_TICKET_MSG_SENDER FOREIGN KEY (sender_user_id) REFERENCES admin_users (id),
    CONSTRAINT CK_TICKET_MSG_SENDER_TYPE CHECK (sender_type IN ('USER', 'EMPLOYEE', 'SYSTEM'))
);

CREATE TABLE ticket_attachments (
    id           NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ticket_id    NUMBER(19) NOT NULL,
    message_id   NUMBER(19),
    object_key   VARCHAR2(200 CHAR) NOT NULL,
    file_name    VARCHAR2(255 CHAR) NOT NULL,
    content_type VARCHAR2(100 CHAR) NOT NULL,
    size_bytes   NUMBER(19) NOT NULL,
    uploaded_by  NUMBER(19) NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TICKET_ATTACHMENTS PRIMARY KEY (id),
    CONSTRAINT UQ_TICKET_ATT_OBJECT_KEY UNIQUE (object_key),
    CONSTRAINT FK_TICKET_ATT_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT FK_TICKET_ATT_MESSAGE FOREIGN KEY (message_id) REFERENCES ticket_messages (id),
    CONSTRAINT FK_TICKET_ATT_UPLOADER FOREIGN KEY (uploaded_by) REFERENCES admin_users (id),
    CONSTRAINT CK_TICKET_ATT_SIZE CHECK (size_bytes > 0)
);

CREATE TABLE ticket_events (
    id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ticket_id   NUMBER(19) NOT NULL,
    type        VARCHAR2(30 CHAR) NOT NULL,
    from_status VARCHAR2(20 CHAR),
    to_status   VARCHAR2(20 CHAR),
    employee_id NUMBER(19),
    detail      VARCHAR2(500 CHAR),
    created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TICKET_EVENTS PRIMARY KEY (id),
    CONSTRAINT FK_TICKET_EVT_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT FK_TICKET_EVT_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id),
    CONSTRAINT CK_TICKET_EVT_TYPE CHECK (type IN ('ABERTO', 'ROTEADO', 'ASSUMIDO', 'TRANSFERIDO', 'ESCALADO',
        'RESOLVIDO', 'REABERTO', 'FECHADO', 'ALERTA_ENGENHARIA', 'ERRO_ESCALONAMENTO'))
);

CREATE TABLE notifications (
    id                NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    recipient_user_id NUMBER(19) NOT NULL,
    ticket_id         NUMBER(19),
    type              VARCHAR2(30 CHAR) NOT NULL,
    title             VARCHAR2(150 CHAR) NOT NULL,
    body              VARCHAR2(500 CHAR) NOT NULL,
    read_at           TIMESTAMP(6) WITH TIME ZONE,
    created_at        TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NOTIFICATIONS PRIMARY KEY (id),
    CONSTRAINT FK_NOTIF_RECIPIENT FOREIGN KEY (recipient_user_id) REFERENCES admin_users (id),
    CONSTRAINT FK_NOTIF_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT CK_NOTIF_TYPE CHECK (type IN ('TICKET_ATRIBUIDO', 'TICKET_ASSUMIDO', 'NOVA_MENSAGEM',
        'TICKET_RESOLVIDO', 'TICKET_ESCALADO', 'ALERTA_ENGENHARIA', 'TICKET_FECHADO'))
);

-- Índices de FK (o Oracle não os cria sozinho) e de consulta.
CREATE INDEX IX_EMP_SKILLS_SKILL ON employee_skills (skill_id);
CREATE INDEX IX_TIPO_CONFIG_SKILL ON ticket_tipo_config (skill_id);
CREATE INDEX IX_TICKETS_USER ON tickets (user_id);
CREATE INDEX IX_TICKETS_EMPLOYEE ON tickets (assigned_employee_id);
CREATE INDEX IX_TICKETS_SEGMENT_STATUS ON tickets (segment, status);
CREATE INDEX IX_TICKETS_STATUS_SLA ON tickets (status, sla_due_at);
CREATE INDEX IX_TICKET_MSG_TICKET ON ticket_messages (ticket_id);
CREATE INDEX IX_TICKET_MSG_SENDER ON ticket_messages (sender_user_id);
CREATE INDEX IX_TICKET_ATT_TICKET ON ticket_attachments (ticket_id);
CREATE INDEX IX_TICKET_ATT_MESSAGE ON ticket_attachments (message_id);
CREATE INDEX IX_TICKET_ATT_UPLOADER ON ticket_attachments (uploaded_by);
CREATE INDEX IX_TICKET_EVT_TICKET ON ticket_events (ticket_id);
CREATE INDEX IX_TICKET_EVT_EMPLOYEE ON ticket_events (employee_id);
CREATE INDEX IX_NOTIF_RECIPIENT_READ ON notifications (recipient_user_id, read_at);
CREATE INDEX IX_NOTIF_TICKET ON notifications (ticket_id);

-- Dados de referência: sem eles o roteamento não funciona.
INSERT INTO skills (code, name) VALUES ('DESENVOLVEDOR', 'Desenvolvedor / Suporte T3');
INSERT INTO skills (code, name) VALUES ('GESTAO_ENTREGAS', 'Gestão de Entregas / Logística');
INSERT INTO skills (code, name) VALUES ('PRODUTO_MELHORIAS', 'Produto / Melhorias');

INSERT INTO ticket_tipo_config (segment, label, skill_id, queue, default_priority, sla_minutes, escalation_minutes)
SELECT 'DEFEITO_APP', 'Defeito no App / Problemas com App', id, 'TECNOLOGIA', 'ALTA', 240, 60
  FROM skills WHERE code = 'DESENVOLVEDOR';
INSERT INTO ticket_tipo_config (segment, label, skill_id, queue, default_priority, sla_minutes, escalation_minutes)
SELECT 'PROBLEMA_PEDIDO', 'Problemas com pedido', id, 'MARKETPLACE', 'NORMAL', 480, 120
  FROM skills WHERE code = 'GESTAO_ENTREGAS';
INSERT INTO ticket_tipo_config (segment, label, skill_id, queue, default_priority, sla_minutes, escalation_minutes)
SELECT 'FEEDBACK_SUGESTAO', 'Feedback / Sugestões', id, 'PRODUTO', 'NORMAL', 2880, 720
  FROM skills WHERE code = 'PRODUTO_MELHORIAS';
