-- Chatbot nível 0 (Mentor Edu): FAQ com palavras-chave, conversas e mensagens.

CREATE TABLE chatbot_faq (
    id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    segment    VARCHAR2(30 CHAR)   NOT NULL,
    question   VARCHAR2(200 CHAR)  NOT NULL,
    answer     VARCHAR2(1000 CHAR) NOT NULL,
    sort_order NUMBER(3)           NOT NULL,
    active     BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT PK_CHATBOT_FAQ PRIMARY KEY (id),
    CONSTRAINT FK_CHATBOT_FAQ_SEGMENT FOREIGN KEY (segment) REFERENCES ticket_tipo_config (segment)
);

-- A palavra é gravada já normalizada (minúsculas, sem acento) e como radical,
-- porque a FN_CHATBOT_RESPOSTA compara com INSTR no texto normalizado.
CREATE TABLE chatbot_faq_keywords (
    faq_id  NUMBER(19)        NOT NULL,
    keyword VARCHAR2(40 CHAR) NOT NULL,
    CONSTRAINT PK_CHATBOT_FAQ_KEYWORDS PRIMARY KEY (faq_id, keyword),
    CONSTRAINT FK_CHATBOT_KEYWORDS_FAQ FOREIGN KEY (faq_id) REFERENCES chatbot_faq (id),
    CONSTRAINT CK_CHATBOT_KEYWORDS_NORMALIZED CHECK (REGEXP_LIKE(keyword, '^[a-z0-9]+$'))
);

CREATE TABLE chatbot_conversations (
    id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id        NUMBER(19) NOT NULL,
    segment        VARCHAR2(30 CHAR),
    state          VARCHAR2(20 CHAR) DEFAULT 'INICIO' NOT NULL,
    misses         NUMBER(3) DEFAULT 0 NOT NULL,
    current_faq_id NUMBER(19),
    ticket_id      NUMBER(19),
    created_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    finished_at    TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_CHATBOT_CONVERSATIONS PRIMARY KEY (id),
    CONSTRAINT UQ_CHATBOT_CONV_TICKET UNIQUE (ticket_id),
    CONSTRAINT FK_CHATBOT_CONV_USER FOREIGN KEY (user_id) REFERENCES admin_users (id),
    CONSTRAINT FK_CHATBOT_CONV_SEGMENT FOREIGN KEY (segment) REFERENCES ticket_tipo_config (segment),
    CONSTRAINT FK_CHATBOT_CONV_FAQ FOREIGN KEY (current_faq_id) REFERENCES chatbot_faq (id),
    CONSTRAINT FK_CHATBOT_CONV_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT CK_CHATBOT_CONV_STATE CHECK (state IN ('INICIO', 'SEGMENTO', 'CONFIRMACAO', 'ENCAMINHAMENTO',
        'RESOLVIDA', 'ENCAMINHADA')),
    CONSTRAINT CK_CHATBOT_CONV_MISSES CHECK (misses >= 0)
);

-- option_id: a opção que o usuário tocou; nulo quando ele digitou. É o que
-- separa os textos livres (que vão para a descrição do ticket) das escolhas.
CREATE TABLE chatbot_messages (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    conversation_id NUMBER(19) NOT NULL,
    sender          VARCHAR2(10 CHAR) NOT NULL,
    body            VARCHAR2(1000 CHAR) NOT NULL,
    option_id       VARCHAR2(40 CHAR),
    faq_id          NUMBER(19),
    created_at      TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CHATBOT_MESSAGES PRIMARY KEY (id),
    CONSTRAINT FK_CHATBOT_MSG_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES chatbot_conversations (id),
    CONSTRAINT FK_CHATBOT_MSG_FAQ FOREIGN KEY (faq_id) REFERENCES chatbot_faq (id),
    CONSTRAINT CK_CHATBOT_MSG_SENDER CHECK (sender IN ('BOT', 'USER'))
);

-- Índices de FK e de consulta. UQ_CHATBOT_CONV_TICKET e a PK das palavras-chave
-- já cobrem ticket_id e faq_id.
CREATE INDEX IX_CHATBOT_FAQ_SEGMENT_ORDER ON chatbot_faq (segment, sort_order);
CREATE INDEX IX_CHATBOT_CONV_USER ON chatbot_conversations (user_id);
CREATE INDEX IX_CHATBOT_CONV_SEGMENT ON chatbot_conversations (segment);
CREATE INDEX IX_CHATBOT_CONV_FAQ ON chatbot_conversations (current_faq_id);
CREATE INDEX IX_CHATBOT_MSG_CONVERSATION ON chatbot_messages (conversation_id, id);
CREATE INDEX IX_CHATBOT_MSG_FAQ ON chatbot_messages (faq_id);
