-- DDL consolidado do Edu Admin (Oracle 23ai), para importar no SQL Developer
-- Data Modeler (File > Import > DDL File) e montar o DER.
--
-- Junta as migrations V1, V3, V5 e V8 de api/src/main/resources/db/migration/
-- num só arquivo: 19 tabelas, com PK, FK, UQ e CHECK nomeadas, e os 29 índices
-- explícitos. Não tem seed, dados de referência nem PL/SQL. Não substitui as
-- migrations: o Flyway continua sendo o dono do schema.
--
-- Roda de uma vez num schema vazio. Depois de mudar as migrations, atualize
-- este arquivo e rode docs/banco-de-dados/conferir-ddl.sh.

-- ============================================================================
-- Edu Admin (V1): usuários, produtos, estoque e transportadoras
-- ============================================================================

CREATE TABLE products (
    id            NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name          VARCHAR2(150 CHAR) NOT NULL,
    sku           VARCHAR2(60 CHAR)  NOT NULL,
    description   VARCHAR2(500 CHAR),
    price         NUMBER(10,2) DEFAULT 0 NOT NULL,
    minimum_stock NUMBER(10) NOT NULL,
    active        BOOLEAN DEFAULT TRUE NOT NULL,
    created_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at    TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_PRODUCTS PRIMARY KEY (id),
    CONSTRAINT UQ_PRODUCTS_SKU UNIQUE (sku),
    CONSTRAINT CK_PRODUCTS_MINIMUM_STOCK CHECK (minimum_stock >= 0),
    CONSTRAINT CK_PRODUCTS_PRICE CHECK (price >= 0)
);

CREATE TABLE inventories (
    id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    product_id NUMBER(19) NOT NULL,
    quantity   NUMBER(10) DEFAULT 0 NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_INVENTORIES PRIMARY KEY (id),
    CONSTRAINT UQ_INVENTORIES_PRODUCT UNIQUE (product_id),
    CONSTRAINT FK_INVENTORIES_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id),
    CONSTRAINT CK_INVENTORIES_QUANTITY CHECK (quantity >= 0)
);

CREATE INDEX IX_INVENTORIES_QUANTITY ON inventories (quantity);

CREATE TABLE inventory_adjustments (
    id                NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    inventory_id      NUMBER(19) NOT NULL,
    previous_quantity NUMBER(10) NOT NULL,
    new_quantity      NUMBER(10) NOT NULL,
    reason            VARCHAR2(300 CHAR) NOT NULL,
    created_at        TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_INVENTORY_ADJUSTMENTS PRIMARY KEY (id),
    CONSTRAINT FK_INV_ADJ_INVENTORY FOREIGN KEY (inventory_id) REFERENCES inventories (id),
    CONSTRAINT CK_INV_ADJ_PREVIOUS_QTY CHECK (previous_quantity >= 0),
    CONSTRAINT CK_INV_ADJ_NEW_QTY CHECK (new_quantity >= 0)
);

CREATE INDEX IX_INV_ADJ_INVENTORY ON inventory_adjustments (inventory_id);

CREATE TABLE carriers (
    id                    NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name                  VARCHAR2(150 CHAR) NOT NULL,
    location              VARCHAR2(150 CHAR) NOT NULL,
    email                 VARCHAR2(254 CHAR) NOT NULL,
    average_delivery_days NUMBER(10) NOT NULL,
    rating                NUMBER(2,1) NOT NULL,
    sla_percentage        NUMBER(5,2) NOT NULL,
    status                VARCHAR2(20 CHAR) NOT NULL,
    created_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at            TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CARRIERS PRIMARY KEY (id),
    CONSTRAINT CK_CARRIERS_DELIVERY_DAYS CHECK (average_delivery_days > 0),
    CONSTRAINT CK_CARRIERS_RATING CHECK (rating >= 0 AND rating <= 5),
    CONSTRAINT CK_CARRIERS_SLA CHECK (sla_percentage >= 0 AND sla_percentage <= 100),
    CONSTRAINT CK_CARRIERS_STATUS CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

CREATE INDEX IX_CARRIERS_STATUS ON carriers (status);

CREATE TABLE carrier_occurrences (
    id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    carrier_id  NUMBER(19) NOT NULL,
    type        VARCHAR2(30 CHAR) NOT NULL,
    description VARCHAR2(500 CHAR) NOT NULL,
    status      VARCHAR2(20 CHAR) DEFAULT 'OPEN' NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    resolved_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_CARRIER_OCCURRENCES PRIMARY KEY (id),
    CONSTRAINT FK_CARRIER_OCC_CARRIER FOREIGN KEY (carrier_id) REFERENCES carriers (id),
    CONSTRAINT CK_CARRIER_OCC_TYPE CHECK (type IN ('DELIVERY_DELAY', 'DAMAGE', 'DELIVERY_FAILURE', 'OTHER')),
    CONSTRAINT CK_CARRIER_OCC_STATUS CHECK (status IN ('OPEN', 'RESOLVED'))
);

CREATE INDEX IX_CARRIER_OCC_CARRIER ON carrier_occurrences (carrier_id);
CREATE INDEX IX_CARRIER_OCC_STATUS ON carrier_occurrences (status);

-- CK_ADMIN_USERS_ROLE vem da V3 (ALTER TABLE); aqui entra no próprio CREATE TABLE.
CREATE TABLE admin_users (
    id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name       VARCHAR2(150 CHAR) NOT NULL,
    email      VARCHAR2(254 CHAR) NOT NULL,
    password   VARCHAR2(255 CHAR) NOT NULL,
    role       VARCHAR2(20 CHAR)  NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_ADMIN_USERS PRIMARY KEY (id),
    CONSTRAINT UQ_ADMIN_USERS_EMAIL UNIQUE (email),
    CONSTRAINT CK_ADMIN_USERS_ROLE CHECK (role IN ('USER', 'EMPLOYEE', 'ADMIN'))
);

-- ============================================================================
-- Atendimento omnichannel (V3): atendentes, skills, matriz de triagem, tickets,
-- conversa, anexos, trilha de eventos e notificações
-- ============================================================================

CREATE TABLE skills (
    id   NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    code VARCHAR2(40 CHAR)  NOT NULL,
    name VARCHAR2(100 CHAR) NOT NULL,
    CONSTRAINT PK_SKILLS PRIMARY KEY (id),
    CONSTRAINT UQ_SKILLS_CODE UNIQUE (code)
);

CREATE TABLE employees (
    id                  NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id             NUMBER(19) NOT NULL,
    presence            VARCHAR2(10 CHAR) DEFAULT 'OFFLINE' NOT NULL,
    presence_changed_at TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    last_assigned_at    TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (id),
    CONSTRAINT UQ_EMPLOYEES_USER UNIQUE (user_id),
    CONSTRAINT FK_EMPLOYEES_USER FOREIGN KEY (user_id) REFERENCES admin_users (id),
    CONSTRAINT CK_EMPLOYEES_PRESENCE CHECK (presence IN ('ONLINE', 'AUSENTE', 'OFFLINE'))
);

CREATE TABLE employee_skills (
    employee_id NUMBER(19) NOT NULL,
    skill_id    NUMBER(19) NOT NULL,
    CONSTRAINT PK_EMPLOYEE_SKILLS PRIMARY KEY (employee_id, skill_id),
    CONSTRAINT FK_EMP_SKILLS_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id),
    CONSTRAINT FK_EMP_SKILLS_SKILL FOREIGN KEY (skill_id) REFERENCES skills (id)
);

CREATE INDEX IX_EMP_SKILLS_SKILL ON employee_skills (skill_id);

CREATE TABLE ticket_tipo_config (
    segment            VARCHAR2(30 CHAR)  NOT NULL,
    label              VARCHAR2(100 CHAR) NOT NULL,
    skill_id           NUMBER(19) NOT NULL,
    queue              VARCHAR2(20 CHAR)  NOT NULL,
    default_priority   VARCHAR2(10 CHAR)  NOT NULL,
    sla_minutes        NUMBER(10) NOT NULL,
    escalation_minutes NUMBER(10) NOT NULL,
    active             BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT PK_TICKET_TIPO_CONFIG PRIMARY KEY (segment),
    CONSTRAINT FK_TIPO_CONFIG_SKILL FOREIGN KEY (skill_id) REFERENCES skills (id),
    CONSTRAINT CK_TIPO_CONFIG_SEGMENT CHECK (segment IN ('DEFEITO_APP', 'PROBLEMA_PEDIDO', 'FEEDBACK_SUGESTAO')),
    CONSTRAINT CK_TIPO_CONFIG_QUEUE CHECK (queue IN ('TECNOLOGIA', 'MARKETPLACE', 'PRODUTO')),
    CONSTRAINT CK_TIPO_CONFIG_PRIORITY CHECK (default_priority IN ('NORMAL', 'ALTA', 'CRITICA')),
    CONSTRAINT CK_TIPO_CONFIG_MINUTES CHECK (sla_minutes > 0 AND escalation_minutes > 0)
);

CREATE INDEX IX_TIPO_CONFIG_SKILL ON ticket_tipo_config (skill_id);

CREATE TABLE tickets (
    id                       NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id                  NUMBER(19) NOT NULL,
    segment                  VARCHAR2(30 CHAR) NOT NULL,
    description              VARCHAR2(2000 CHAR) NOT NULL,
    channel                  VARCHAR2(20 CHAR) DEFAULT 'APP' NOT NULL,
    status                   VARCHAR2(20 CHAR) DEFAULT 'ABERTO' NOT NULL,
    priority                 VARCHAR2(10 CHAR) DEFAULT 'NORMAL' NOT NULL,
    assigned_employee_id     NUMBER(19),
    sla_started_at           TIMESTAMP(6) WITH TIME ZONE,
    sla_due_at               TIMESTAMP(6) WITH TIME ZONE,
    engineering_alert        BOOLEAN DEFAULT FALSE NOT NULL,
    engineering_alert_reason VARCHAR2(500 CHAR),
    created_at               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at               TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    assumed_at               TIMESTAMP(6) WITH TIME ZONE,
    resolved_at              TIMESTAMP(6) WITH TIME ZONE,
    closed_at                TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_TICKETS PRIMARY KEY (id),
    CONSTRAINT FK_TICKETS_USER FOREIGN KEY (user_id) REFERENCES admin_users (id),
    CONSTRAINT FK_TICKETS_SEGMENT FOREIGN KEY (segment) REFERENCES ticket_tipo_config (segment),
    CONSTRAINT FK_TICKETS_EMPLOYEE FOREIGN KEY (assigned_employee_id) REFERENCES employees (id),
    CONSTRAINT CK_TICKETS_CHANNEL CHECK (channel IN ('APP', 'CHATBOT_IA')),
    CONSTRAINT CK_TICKETS_STATUS CHECK (status IN ('ABERTO', 'EM_FILA', 'EM_ATENDIMENTO', 'ESCALADO', 'RESOLVIDO', 'FECHADO')),
    CONSTRAINT CK_TICKETS_PRIORITY CHECK (priority IN ('NORMAL', 'ALTA', 'CRITICA'))
);

CREATE INDEX IX_TICKETS_USER ON tickets (user_id);
CREATE INDEX IX_TICKETS_EMPLOYEE ON tickets (assigned_employee_id);
CREATE INDEX IX_TICKETS_SEGMENT_STATUS ON tickets (segment, status);
CREATE INDEX IX_TICKETS_STATUS_SLA ON tickets (status, sla_due_at);
-- V8: agregações do dashboard (PR_RESUMO_DASHBOARD).
CREATE INDEX IX_TICKETS_CREATED ON tickets (created_at);
CREATE INDEX IX_TICKETS_RESOLVED ON tickets (resolved_at);

CREATE TABLE ticket_messages (
    id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ticket_id      NUMBER(19) NOT NULL,
    sender_type    VARCHAR2(10 CHAR) NOT NULL,
    sender_user_id NUMBER(19),
    body           VARCHAR2(2000 CHAR) NOT NULL,
    created_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TICKET_MESSAGES PRIMARY KEY (id),
    CONSTRAINT FK_TICKET_MSG_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT FK_TICKET_MSG_SENDER FOREIGN KEY (sender_user_id) REFERENCES admin_users (id),
    CONSTRAINT CK_TICKET_MSG_SENDER_TYPE CHECK (sender_type IN ('USER', 'EMPLOYEE', 'SYSTEM'))
);

CREATE INDEX IX_TICKET_MSG_TICKET ON ticket_messages (ticket_id);
CREATE INDEX IX_TICKET_MSG_SENDER ON ticket_messages (sender_user_id);

CREATE TABLE ticket_attachments (
    id           NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ticket_id    NUMBER(19) NOT NULL,
    message_id   NUMBER(19),
    object_key   VARCHAR2(200 CHAR) NOT NULL,
    file_name    VARCHAR2(255 CHAR) NOT NULL,
    content_type VARCHAR2(100 CHAR) NOT NULL,
    size_bytes   NUMBER(19) NOT NULL,
    uploaded_by  NUMBER(19) NOT NULL,
    created_at   TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TICKET_ATTACHMENTS PRIMARY KEY (id),
    CONSTRAINT UQ_TICKET_ATT_OBJECT_KEY UNIQUE (object_key),
    CONSTRAINT FK_TICKET_ATT_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT FK_TICKET_ATT_MESSAGE FOREIGN KEY (message_id) REFERENCES ticket_messages (id),
    CONSTRAINT FK_TICKET_ATT_UPLOADER FOREIGN KEY (uploaded_by) REFERENCES admin_users (id),
    CONSTRAINT CK_TICKET_ATT_SIZE CHECK (size_bytes > 0)
);

CREATE INDEX IX_TICKET_ATT_TICKET ON ticket_attachments (ticket_id);
CREATE INDEX IX_TICKET_ATT_MESSAGE ON ticket_attachments (message_id);
CREATE INDEX IX_TICKET_ATT_UPLOADER ON ticket_attachments (uploaded_by);

CREATE TABLE ticket_events (
    id          NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    ticket_id   NUMBER(19) NOT NULL,
    type        VARCHAR2(30 CHAR) NOT NULL,
    from_status VARCHAR2(20 CHAR),
    to_status   VARCHAR2(20 CHAR),
    employee_id NUMBER(19),
    detail      VARCHAR2(500 CHAR),
    created_at  TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TICKET_EVENTS PRIMARY KEY (id),
    CONSTRAINT FK_TICKET_EVT_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT FK_TICKET_EVT_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employees (id),
    CONSTRAINT CK_TICKET_EVT_TYPE CHECK (type IN ('ABERTO', 'ROTEADO', 'ASSUMIDO', 'TRANSFERIDO', 'ESCALADO',
        'RESOLVIDO', 'REABERTO', 'FECHADO', 'ALERTA_ENGENHARIA', 'ERRO_ESCALONAMENTO'))
);

CREATE INDEX IX_TICKET_EVT_TICKET ON ticket_events (ticket_id);
CREATE INDEX IX_TICKET_EVT_EMPLOYEE ON ticket_events (employee_id);
-- V8: agregações do dashboard (PR_RESUMO_DASHBOARD).
CREATE INDEX IX_TICKET_EVT_TYPE_CREATED ON ticket_events (type, created_at);

CREATE TABLE notifications (
    id                NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    recipient_user_id NUMBER(19) NOT NULL,
    ticket_id         NUMBER(19),
    type              VARCHAR2(30 CHAR) NOT NULL,
    title             VARCHAR2(150 CHAR) NOT NULL,
    body              VARCHAR2(500 CHAR) NOT NULL,
    read_at           TIMESTAMP(6) WITH TIME ZONE,
    created_at        TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_NOTIFICATIONS PRIMARY KEY (id),
    CONSTRAINT FK_NOTIF_RECIPIENT FOREIGN KEY (recipient_user_id) REFERENCES admin_users (id),
    CONSTRAINT FK_NOTIF_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT CK_NOTIF_TYPE CHECK (type IN ('TICKET_ATRIBUIDO', 'TICKET_ASSUMIDO', 'NOVA_MENSAGEM',
        'TICKET_RESOLVIDO', 'TICKET_ESCALADO', 'ALERTA_ENGENHARIA', 'TICKET_FECHADO'))
);

CREATE INDEX IX_NOTIF_RECIPIENT_READ ON notifications (recipient_user_id, read_at);
CREATE INDEX IX_NOTIF_TICKET ON notifications (ticket_id);

-- ============================================================================
-- Chatbot nível 0 (V5): FAQ com palavras-chave, conversas e mensagens
-- ============================================================================

CREATE TABLE chatbot_faq (
    id         NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    segment    VARCHAR2(30 CHAR)   NOT NULL,
    question   VARCHAR2(200 CHAR)  NOT NULL,
    answer     VARCHAR2(1000 CHAR) NOT NULL,
    sort_order NUMBER(3)           NOT NULL,
    active     BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT PK_CHATBOT_FAQ PRIMARY KEY (id),
    CONSTRAINT FK_CHATBOT_FAQ_SEGMENT FOREIGN KEY (segment) REFERENCES ticket_tipo_config (segment)
);

CREATE INDEX IX_CHATBOT_FAQ_SEGMENT_ORDER ON chatbot_faq (segment, sort_order);

-- A palavra é gravada já normalizada (minúsculas, sem acento) e como radical,
-- porque a FN_CHATBOT_RESPOSTA compara com INSTR no texto normalizado.
CREATE TABLE chatbot_faq_keywords (
    faq_id  NUMBER(19)        NOT NULL,
    keyword VARCHAR2(40 CHAR) NOT NULL,
    CONSTRAINT PK_CHATBOT_FAQ_KEYWORDS PRIMARY KEY (faq_id, keyword),
    CONSTRAINT FK_CHATBOT_KEYWORDS_FAQ FOREIGN KEY (faq_id) REFERENCES chatbot_faq (id),
    CONSTRAINT CK_CHATBOT_KEYWORDS_NORMALIZED CHECK (REGEXP_LIKE(keyword, '^[a-z0-9]+$'))
);

CREATE TABLE chatbot_conversations (
    id             NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id        NUMBER(19) NOT NULL,
    segment        VARCHAR2(30 CHAR),
    state          VARCHAR2(20 CHAR) DEFAULT 'INICIO' NOT NULL,
    misses         NUMBER(3) DEFAULT 0 NOT NULL,
    current_faq_id NUMBER(19),
    ticket_id      NUMBER(19),
    created_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at     TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    finished_at    TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT PK_CHATBOT_CONVERSATIONS PRIMARY KEY (id),
    CONSTRAINT UQ_CHATBOT_CONV_TICKET UNIQUE (ticket_id),
    CONSTRAINT FK_CHATBOT_CONV_USER FOREIGN KEY (user_id) REFERENCES admin_users (id),
    CONSTRAINT FK_CHATBOT_CONV_SEGMENT FOREIGN KEY (segment) REFERENCES ticket_tipo_config (segment),
    CONSTRAINT FK_CHATBOT_CONV_FAQ FOREIGN KEY (current_faq_id) REFERENCES chatbot_faq (id),
    CONSTRAINT FK_CHATBOT_CONV_TICKET FOREIGN KEY (ticket_id) REFERENCES tickets (id),
    CONSTRAINT CK_CHATBOT_CONV_STATE CHECK (state IN ('INICIO', 'SEGMENTO', 'CONFIRMACAO', 'ENCAMINHAMENTO',
        'RESOLVIDA', 'ENCAMINHADA')),
    CONSTRAINT CK_CHATBOT_CONV_MISSES CHECK (misses >= 0)
);

CREATE INDEX IX_CHATBOT_CONV_USER ON chatbot_conversations (user_id);
CREATE INDEX IX_CHATBOT_CONV_SEGMENT ON chatbot_conversations (segment);
CREATE INDEX IX_CHATBOT_CONV_FAQ ON chatbot_conversations (current_faq_id);

-- option_id: a opção que o usuário tocou; nulo quando ele digitou. É o que
-- separa os textos livres (que vão para a descrição do ticket) das escolhas.
CREATE TABLE chatbot_messages (
    id              NUMBER(19) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    conversation_id NUMBER(19) NOT NULL,
    sender          VARCHAR2(10 CHAR) NOT NULL,
    body            VARCHAR2(1000 CHAR) NOT NULL,
    option_id       VARCHAR2(40 CHAR),
    faq_id          NUMBER(19),
    created_at      TIMESTAMP(6) WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_CHATBOT_MESSAGES PRIMARY KEY (id),
    CONSTRAINT FK_CHATBOT_MSG_CONVERSATION FOREIGN KEY (conversation_id) REFERENCES chatbot_conversations (id),
    CONSTRAINT FK_CHATBOT_MSG_FAQ FOREIGN KEY (faq_id) REFERENCES chatbot_faq (id),
    CONSTRAINT CK_CHATBOT_MSG_SENDER CHECK (sender IN ('BOT', 'USER'))
);

CREATE INDEX IX_CHATBOT_MSG_CONVERSATION ON chatbot_messages (conversation_id, id);
CREATE INDEX IX_CHATBOT_MSG_FAQ ON chatbot_messages (faq_id);
